# Generated by Django 4.0.1 on 2022-01-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack',
            old_name='attack_num',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='defense',
            name='dense_num',
        ),
        migrations.AddField(
            model_name='defense',
            name='num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cardgame.card'),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='attack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardgame.attack'),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='defense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cardgame.defense'),
        ),
    ]
