# Generated by Django 4.0.1 on 2022-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_alter_cardgame_mode_alter_cardgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgame',
            name='status',
            field=models.CharField(choices=[('끝', '끝'), ('진행중', '진행중')], max_length=20),
        ),
    ]
