# Generated by Django 4.0.1 on 2022-01-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0002_rename_attack_num_attack_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defense',
            name='num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardgame.card'),
        ),
    ]
