# Generated by Django 3.2 on 2022-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_alter_cardgame_mode_alter_cardgame_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardgame',
            name='mode',
            field=models.CharField(choices=[('작은 수', '작은 수'), ('큰 수', '큰 수')], max_length=20),
        ),
    ]
