# Generated by Django 4.0.1 on 2022-01-20 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardgame', '0004_alter_cardgame_mode_alter_cardgame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgame',
            name='victory_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardgame',
            name='mode',
            field=models.CharField(choices=[('작은 수', '작은 수'), ('큰 수', '큰 수')], max_length=20),
        ),
    ]
